groups:
  - name: velero.rules
    rules:
      - expr: 'sum by(schedule) (velero_backup_failure_total{schedule!=""} - velero_backup_failure_total offset 10m)'
        record: velero_schedule_failure_increment
      - expr: 'sum by(schedule) (velero_backup_partial_failure_total{schedule!=""} - velero_backup_partial_failure_total offset 10m)'
        record: velero_schedule_partial_failure_increment

      - alert: VeleroBackupFailure
        annotations:
          message: 'Failed backup in Velero schedule {{ $labels.schedule }}.'
        expr: 'velero_schedule_failure_increment > 0'
        for: 15s
        labels:
          resolves: never
          scope: cluster
          severity: P3-Minor

      - alert: VeleroBackupPartialFailure
        annotations:
          message: 'Partially failed backup in Velero schedule {{ $labels.schedule }}.'
        expr: 'velero_schedule_partial_failure_increment > 0'
        for: 15s
        labels:
          resolves: never
          scope: cluster
          severity: P3-Minor

      - alert: ContinuousVeleroBackupFailure
        annotations:
          message: 'Continuous failed backup in Velero schedule {{ $labels.schedule }}!'
        expr: 'velero_schedule_failure_increment > 1'
        for: 10m
        labels:
          scope: cluster
          severity: P1-Critical

      - alert: ContinuousVeleroBackupPartialFailure
        annotations:
          message: 'Continuous partially failed backup in Velero schedule {{ $labels.schedule }}!'
        expr: 'velero_schedule_partial_failure_increment > 1'
        for: 10m
        labels:
          scope: cluster
          severity: P1-Critical

      - alert: VeleroBackupTakingLongTime
        annotations:
          message: 'A Velero backup for schedule {{ $labels.schedule }} is taking longer then 2 hours and 30 minutes.'
        expr: 'sum by(schedule) (changes(velero_backup_attempt_total{schedule!=""}[48h])) > 0 unless sum by(schedule) ((changes(velero_backup_success_total{schedule!=""}[2h30m]) + changes(velero_backup_partial_failure_total{schedule!=""}[2h30m]) + changes(velero_backup_failure_total{schedule!=""}[2h30m]) + changes(velero_backup_validation_failure_total{schedule!=""}[2h30m])) > 0)'
        for: 1m
        labels:
          resolves: never
          scope: cluster
          severity: P2-Major

      - alert: VeleroHourlyBackupFailure
        annotations:
          message: 'Hourly failure in backup schedule {{ $labels.schedule }}!'
        expr: 'sum by(schedule) (velero_backup_failure_total{schedule="velero-hourly-resources"} - velero_backup_failure_total{schedule="velero-hourly-resources"} offset 160m > 1)'
        for: 15s
        labels:
          scope: cluster
          severity: P2-Major

      - alert: VeleroHourlyBackupPartialFailure
        annotations:
          message: 'Hourly partial failure in backup schedule {{ $labels.schedule }}.'
        expr: 'sum by(schedule) (velero_backup_partial_failure_total{schedule="velero-hourly-resources"} - velero_backup_partial_failure_total{schedule="velero-hourly-resources"} offset 160m > 1)'
        for: 15s
        labels:
          scope: cluster
          severity: P2-Major
